trigger:
  - "*"

variables:
  buildConfiguration: "Release"
  releaseBranchName: "release"

schedules:
  - cron: "0 3 * * *"
    displayName: "Deploy every day at 3 A.M."
    branches:
      include:
        - release
    always: false

stages:
  - stage: "Build"
    displayName: "Build the web application"
    jobs:
      - job: "Build"
        displayName: "Build job"
        pool:
          vmImage: "ubuntu-latest"
          demands:
            - npm
        variables:
          wwwrootDir: "Tailspin.SpaceGame.Web/wwwroot"
          dotnetSdkVersion: "6.x"
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET SDK $(dotnetSdkVersion)"
            inputs:
              version: "$(dotnetSdkVersion)"

          # MODIFICATION 1: Add NodeTool@0 to explicitly set Node.js version
          - task: NodeTool@0
            displayName: "Install Node.js 18.x" # Or '20.x' if you prefer
            inputs:
              versionSpec: "18.x" # Use a stable LTS version for consistency

          - task: Npm@1
            displayName: "Run npm install"
            inputs:
              command: "install" # Explicitly use 'install' command
              verbose: false
              # MODIFICATION 2: Specify workingDirectory for npm install
              workingDirectory: "Tailspin.SpaceGame.Web"

          # MODIFICATION 3: Replace old node-sass script with Gulp task
          # The previous 'script' task attempting to run node-sass directly is removed
          # - script: "./node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)"
          #   displayName: "Compile Sass assets"
          # Now, Gulp handles the min:css (which would include Sass if configured in gulpfile)
          - task: Gulp@1
            displayName: "Run Gulp build tasks (min:js, min:css)"
            inputs:
              gulpFile: "Tailspin.SpaceGame.Web/gulpfile.js" # Path to your gulpfile
              targets: "min" # This will run your 'min' task which includes 'min:js' and 'min:css'
              # Specify workingDirectory for gulp task
              workingDirectory: "Tailspin.SpaceGame.Web"

          - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
            displayName: "Write build info"
            # MODIFICATION (ensure this working directory is correct for this script too)
            workingDirectory: $(wwwrootDir)

          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "**/*.csproj"
          - task: DotNetCoreCLI@2
            displayName: "Build the project - $(buildConfiguration)"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration $(buildConfiguration)"
              projects: "**/*.csproj"
          - task: DotNetCoreCLI@2
            displayName: "Publish the project - $(buildConfiguration)"
            inputs:
              command: "publish"
              projects: "**/*.csproj"
              publishWebProjects: false
              arguments: "--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)"
              zipAfterPublish: true
          - publish: "$(Build.ArtifactStagingDirectory)"
            artifact: drop

  - stage: "Dev"
    displayName: "Deploy to the dev environment"
    dependsOn: Build
    condition: |
      and
      (
        succeeded(),
        eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])
      )
    jobs:
      - deployment: Deploy
        pool:
          vmImage: "ubuntu-latest"
        environment: dev
        variables:
          - group: Release
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - task: AzureWebApp@1
                  displayName: "Azure App Service Deploy: website"
                  inputs:
                    azureSubscription: "Resource Manager - Tailspin - Space Game"
                    appName: "$(WebAppNameDev)"
                    package: "$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip"

  - stage: "Test"
    displayName: "Deploy to the test environment"
    dependsOn: Dev
    jobs:
      - deployment: Deploy
        pool:
          vmImage: "ubuntu-latest"
        environment: test
        variables:
          - group: "Release"
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - task: AzureWebApp@1
                  displayName: "Azure App Service Deploy: website"
                  inputs:
                    azureSubscription: "Resource Manager - Tailspin - Space Game"
                    appName: "$(WebAppNameTest)"
                    package: "$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip"

  - stage: "Staging"
    displayName: "Deploy to the staging environment"
    dependsOn: Test
    jobs:
      - deployment: Deploy
        pool:
          vmImage: "ubuntu-latest"
        environment: staging
        variables:
          - group: "Release"
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - task: AzureWebApp@1
                  displayName: "Azure App Service Deploy: website"
                  inputs:
                    azureSubscription: "Resource Manager - Tailspin - Space Game"
                    appName: "$(WebAppNameStaging)"
                    package: "$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip"
